[tool.poetry]
name = "etl-exp"
version = "0.1.0"
description = ""
authors = ["Jader <jadermiguelms@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
